version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trivia
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/trivia"
      NODE_ENV: development
    volumes:
      - ./backend:/app   # good for dev hot reload
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
